### ISSUE TITLE
Possible to add shortcut for template literal interpolation?

### ISSUE THREAD

**Issue by jehillert** [yatki/vscode-surround#47]
Hi,
Would it be possible to add a command and shortcut for interpolating selected text inside an ES6 template literal?  It was not too hard to add it myself using your surround.custom template, but I bet people would love it as a default. I spent about an hour looking through the extension Marketplace and could not find one that did it.

    "surround.custom": {
      "interpolateTemplateLiteralSubstring": {
        "label": "interpolate",
        "description": "hello ==> ${hello}",
        "snippet": "\\${$TM_SELECTED_TEXT}$0",
      }
    }

**Comment by yatki** [comment]
I like the idea. I'll add it and publish it as soon as i have time.

**Comment by jehillert** [comment]
Awesome.  Thank  you sir.

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.1.1 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.1.1)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,
