### ISSUE TITLE
Add support for recently used

### ISSUE THREAD

**Issue by ypapouin** [yatki/vscode-surround#49]
Feature request, it would be nice to add support for _recently used_ like VSCode does for the **Command Palette**

**Comment by yatki** [comment]
Loved the idea. I may introduce a `sort` option, to allow users to sort by name or recentUsage. I'll work on this asap.

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.1.1 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.1.1)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,
