### ISSUE TITLE
Hide or remove some of the surrounds

### ISSUE THREAD

**Issue by Flamefire** [yatki/vscode-surround#6]
I want to use this extension for C++ and code in C++ only. Is it possible, to hide or remove some of the surround commands when working with C++?

Not sure if possible, but what would be great is a list of languages one can set for each surround and when the current language is different the command won't show up. E.g. all the JS only commands do not make any sense in C++

**Comment by yatki** [comment]
It's better to leave the issue open, to remind myself to do this in near future :)

**Comment by atscripter** [comment]
@yatki Thank you for a great extension, excellent work!

I have a similar request to this one but is not language-specific. Can you add the ability to simply un-surround a block of code?

**Comment by yatki** [comment]
@atscripter Hmm that's an interesting request and I think we should discuss it in a separate issue. 

But just to give a quick feedback, I think it's gonna be really hard to implement such feature because code blocks can be surrounded by various statements and It's really tricky to make a stable code deletion. 

Could you please share a bit more detail about what's in your mind (in a separate issue) so we can see what we can do?

**Comment by atscripter** [comment]
@yatki 

As requested, here's a feature request with a demo: https://github.com/yatki/vscode-surround/issues/13

**Comment by gauravmak** [comment]
Very useful package. Thanks.

**Comment by FletcherGoss** [comment]
A possible solution to solve this is a `languages` field. It should be an array of strings as some languages have a similar syntax.

You can compare this array against the file the user is currently in to determine which wrappers to show, or to display near the top.

If possible, wrappers should be able to share a name as long as none of their languages match, or one doesn't have language specified.

**Comment by yatki** [comment]
@FletcherGoss thanks for your interest. Actually finally I have more time to focus back on this extension and I'm happy to say that I'll be working on this issue starting from tomorrow. 

I'll see what I can do with also using existing vscode features. But this can definitely be done :)

Cheers,

**Comment by rose-a** [comment]
I'd also find "language support" very useful... maybe you could get some inspiration from vs code snippets... There is a `scope` field there where you can declare for which language the snippet should be displayed. If left empty then its available in all languages (this would also be a backwards-compatible approach).

**Comment by woodgear** [comment]
i want to "language support" either...,it truly useful,without it,i have to add prefix like "go-" or "rust-" in all of my snippets

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.1.1 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.1.1)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,
