### ISSUE TITLE
Surround with Region support for C#

### ISSUE THREAD

**Issue by merdz21snchz** [yatki/vscode-surround#61]
Is it possible to remove the line comment on the start and end region directives in C#?

From:
**_// #region
...
// #endregion_**

To:
**_#region
...
#endregion_**

TIA.

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.1.1 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.1.1)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,
