### ISSUE TITLE
support multi lang snippet according to resourceLangId

### ISSUE THREAD

**Issue by heartacker** [yatki/vscode-surround#65]
for example: when current document is c/cpp file. surround will insert snipest for c/cpp. `resourceLangId==cpp`

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.1.1 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.1.1)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,
