### ISSUE TITLE
Not adhering to selected text

### ISSUE THREAD

**Issue by bszabo44** [yatki/vscode-surround#73]
VS Code v 1.58.2
Just reinstalled this plugin after a computer switch and not using for a couple months...
in html, I often use to put `<em>` or such around a short section of a string/line.  Suddenly seems to not be adhering to my selection, instead surrounding the entire string as it determines.  This was not an issue previously.

`<li><em>You will identify the metal from its work function.</em></li>`
I select "work function" and its surrounds the entire thing.

**Comment by yatki** [comment]
@bszabo44 Thank you very much for reporting the issue. I was able to reproduce it. I'll look into it ASAP.

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.2.1 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.2.1)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,
