### ISSUE TITLE
Multi selection is no longer supported starting from version 1.2.0

### ISSUE THREAD

**Issue by nachopitt** [yatki/vscode-surround#74]
1.1.2 still supports multi selection, but newer versions have this feature kind of broken. By broken I mean that, even though multiple selection lines are "selected" and to each one of them you would like to apply a "surround with" wrapper template, it simply won't work.

I find this feature very useful. Could you please bring it back to newest version?

Thanks in advance. Best regards.

**Comment by yatki** [comment]
Hey @nachopitt.. Thanks for reporting the issue. I already created #70 for that.. 

Tbh, I thought nobody was using that feature, but it's nice to know that someone is finding it useful 😁👍🏻

I'll fix it asap.

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.2.2 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.2.2)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,

**Comment by nachopitt** [comment]
> 🎉 This issue was resolved in version 1.2.2 🎉
> 
> The release is available on:
> 
> * [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
> * [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.2.2)
> 
> Don't forget to update your extension and leave a star :)
> Cheers🖖🏻,

Thanks a lot. I already tried it and it works perfectly!

Thanks again.
