### ISSUE TITLE
Extension Setting for Notifications

### ISSUE THREAD

**Issue by hl2guide** [yatki/vscode-surround#76]
Please add a new boolean setting called "Show notification after each update".

That'd allow us to turn it off.

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.3.0 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.3.0)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,
