### ISSUE TITLE
Custom snippet list is broken after first surround

### ISSUE THREAD

**Issue by haoadoresorange** [yatki/vscode-surround#83]
I have several custom snippet.
I just noticed that, after firing up vscode and use it for the first time, it will be the only option that shows in the custom snippet list after.

For example if I have A B C as custom snippets, I open vscode and use B, after that every command `Surround with` will only have B as the custom one, A and C disappear.

EDIT: I just checked and the error started with ver 1.1.0, when languageId support was introduced. That must be the problem.

![record](https://user-images.githubusercontent.com/22086462/161622471-7a17e694-4d64-49ca-95e7-fd4e6fb8f485.gif)

**Comment by yatki** [comment]
Hey @haoadoresorange thanks for reporting the issue.. I'll look into it asap 👍🏻

**Comment by yatki** [comment]
🎉 This issue was resolved in version 1.3.0 🎉

The release is available on: 
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=yatki.vscode-surround)
- [GitHub release](https://github.com/yatki/vscode-surround/releases/tag/v1.3.0)

Don't forget to update your extension and leave a star :)
Cheers🖖🏻,
