### ISSUE TITLE
default key shotrcut overrides the open last closed file

### ISSUE THREAD

**Issue by capaj** [yatki/vscode-surround#9]
wouldn't it be nicer to have a different default shortcut?
Like ctrl+shift+u for example?

ctrl+shift+t is for opening last closed item which many people use-it's the same in the browser too.

**Comment by yatki** [comment]
@capaj Thank you very much for the issue and submitting the PR. 

You are totally right about that. I considered to use other shortcuts as well before publishing the extension but shortcuts always can conflict with each other with new releases and especially with other extensions.

So I prefer to leave it as it is for the moment since it's really easy to reassign it.
